FROM ubuntu:14.04
MAINTAINER Frank Wittig <frank.wittig@here.com>

##### Install Python #####
RUN apt-get update
RUN apt-get install -y python

##### Copy Application #####
RUN mkdir -p /opt/api-demo
COPY display_data.py /opt/api-demo/display_data.py

##### Default Config #####
ENV PORT 80
ENV TYPE temp
ENV API_HOST api
ENV API_PORT 80

##### Run Application #####
EXPOSE 80
WORKDIR /opt/api-demo
CMD ["python", "display_data.py"]
